SELECT actor_id, first_name, last_name, last_update FROM actor;
SELECT actor_id AS ID, first_name AS Nombre, last_name AS Apellido FROM actor;
SELECT * FROM customer;
SELECT DISTINCT store_id FROM customer;
SELECT DISTINCT customer_id FROM payment;
SELECT * FROM country ORDER BY country DESC;
SELECT * FROM customer ORDER BY first_name ASC;
SELECT store_id, first_name, last_name FROM customer;
SELECT store_id AS Tienda, first_name AS Nombre, last_name AS Apellido FROM customer;
SELECT store_id AS Tienda, first_name AS Nombre, last_name AS Apellido FROM customer ORDER BY Apellido DESC;
SELECT * FROM actor WHERE first_name = 'DAN';
SELECT * FROM city WHERE city = 'London';
SELECT * FROM country WHERE country_id = 102;
SELECT * FROM customer WHERE store_id = 1;
SELECT * FROM inventory WHERE film_id > 50;
SELECT * FROM payment WHERE amount < 3;
SELECT * FROM payment WHERE amount BETWEEN 0.01 AND 2.99;
SELECT * FROM language WHERE name <> 'German'; 
SELECT description, release_year FROM film;
SELECT * FROM film WHERE title = 'IMPACT ALADDIN';